sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "10"

before_install:
  - travis_retry npm install
  - travis_retry npm install typescript

script:
  - npm test
  - tsc --version ; tsc -p test

matrix:
  allow_failures:
  - node_js: "10"

notifications:
  email:
    - travis@nodejitsu.com
  irc: "irc.freenode.org#nodejitsu"
